"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.deletePersonalActivityController = exports.updatePersonalActivityController = exports.createPersonalActivityController = exports.getPersonalActivityInfoController = exports.getPersonalActivitiesInfoController = exports.getPersonalActivitiesController = void 0;
const application_1 = require("../application");
const MySQLRepository_1 = require("./adapters/MySQLRepository");
const controllers_1 = require("./controllers");
const mysqlRepository = new MySQLRepository_1.MySQLRepository();
const getPersonalActivitiesService = new application_1.GetPersonalActivitiesService(mysqlRepository);
const getPersonalActivitiesInfoService = new application_1.GetPersonalActivitiesInfoService(mysqlRepository);
const getPersonalActivityInfoService = new application_1.GetPersonalActivityInfoService(mysqlRepository);
const createPersonalActivityService = new application_1.CreatePersonalActivityService(mysqlRepository);
const updatePersonalActivityService = new application_1.UpdatePersonalActivityService(mysqlRepository);
const deletePersonalActivityService = new application_1.DeletePersonalActivityService(mysqlRepository);
exports.getPersonalActivitiesController = new controllers_1.GetPersonalActivitiesController(getPersonalActivitiesService);
exports.getPersonalActivitiesInfoController = new controllers_1.GetPersonalActivitiesInfoController(getPersonalActivitiesInfoService);
exports.getPersonalActivityInfoController = new controllers_1.GetPersonalActivityInfoController(getPersonalActivityInfoService);
exports.createPersonalActivityController = new controllers_1.CreatePersonalActivityController(createPersonalActivityService);
exports.updatePersonalActivityController = new controllers_1.UpdatePersonalActivityController(updatePersonalActivityService);
exports.deletePersonalActivityController = new controllers_1.DeletePersonalActivityController(deletePersonalActivityService);
