"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.notifyGroupActivityController = exports.getGroupActivitiesController = exports.getGroupActivitiesInfoController = exports.deleteGroupActivityInfoController = exports.updateGroupActivityInfoController = exports.getGroupActivityInfoController = exports.createGroupActivityInfoController = void 0;
const firebaseServices_1 = require("../../core/notification/infraestructure/adapters/firebase/firebaseServices");
const groupDependencies_1 = require("../../group/infraestructure/groupDependencies");
const userDependencies_1 = require("../../user/infraestructure/userDependencies");
const application_1 = require("../application");
const MySQLRepository_1 = require("./adapters/MySQLRepository");
const controllers_1 = require("./controllers");
const mysqlRepository = new MySQLRepository_1.MySQLRepository();
const createGroupActivityInfoService = new application_1.CreateGroupActivityInfoService(mysqlRepository, firebaseServices_1.sendMultipleNotificationService, userDependencies_1.getTokenService, groupDependencies_1.getGroupByIdService);
const getGroupActivityInfoService = new application_1.GetGroupActivityInfoService(mysqlRepository);
const updateGroupActivityInfoService = new application_1.UpdateGroupActivityInfoService(mysqlRepository, userDependencies_1.getTokenService, firebaseServices_1.sendMultipleNotificationService);
const deleteGroupActivityInfoService = new application_1.DeleteGroupActivityInfoService(mysqlRepository, firebaseServices_1.sendMultipleNotificationService, userDependencies_1.getTokenService);
const getGroupActivitiesInfoService = new application_1.GetGroupActivitiesInfoService(mysqlRepository);
const getGroupActivitiesService = new application_1.GetGroupActivitiesService(mysqlRepository);
const notifyGroupActivityService = new application_1.NotifyGroupActivityService(mysqlRepository, userDependencies_1.getTokenService, firebaseServices_1.sendMultipleNotificationService);
exports.createGroupActivityInfoController = new controllers_1.CreateGroupActivityInfoController(createGroupActivityInfoService);
exports.getGroupActivityInfoController = new controllers_1.GetGroupActivityInfoController(getGroupActivityInfoService);
exports.updateGroupActivityInfoController = new controllers_1.UpdateGroupActivityInfoController(updateGroupActivityInfoService);
exports.deleteGroupActivityInfoController = new controllers_1.DeleteGroupActivityInfoController(deleteGroupActivityInfoService);
exports.getGroupActivitiesInfoController = new controllers_1.GetGroupActivitiesInfoController(getGroupActivitiesInfoService);
exports.getGroupActivitiesController = new controllers_1.GetGroupActivitiesController(getGroupActivitiesService);
exports.notifyGroupActivityController = new controllers_1.NotifyGroupActivityController(notifyGroupActivityService);
