"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.addUserAtGroupByTokenController = exports.getUsersAtGroupController = exports.deleteUserAtGroupController = exports.addUserAtGroupController = exports.deleteGroupController = exports.updateGroupController = exports.getGroupByIdController = exports.createGroupController = void 0;
const application_1 = require("../application");
const AddUserByTokenService_1 = require("../application/AddUserByTokenService");
const MySQLRepository_1 = require("./adapters/MySQLRepository");
const UuidRepository_1 = require("./adapters/UuidRepository");
const controllers_1 = require("./controllers");
const mysqlRepository = new MySQLRepository_1.MySQLRepository();
const uuidRepository = new UuidRepository_1.UuidRepository();
const createGroupService = new application_1.CreateGroupService(mysqlRepository, uuidRepository);
const getGroupByIdService = new application_1.GetGroupByIdService(mysqlRepository);
const updateGroupService = new application_1.UpdateGroupService(mysqlRepository);
const deleteGroupService = new application_1.DeleteGroupService(mysqlRepository);
const addUserAtGroupService = new application_1.AddUserAtGroupService(mysqlRepository);
const deleteUserAtGroupService = new application_1.DeleteUserAtGroupService(mysqlRepository);
const getUsersAtGroupService = new application_1.GetUsersAtGroupService(mysqlRepository);
const addUserByTokenService = new AddUserByTokenService_1.AddUserByTokenService(mysqlRepository);
exports.createGroupController = new controllers_1.CreateGroupController(createGroupService);
exports.getGroupByIdController = new controllers_1.GetGroupByIdController(getGroupByIdService);
exports.updateGroupController = new controllers_1.UpdateGroupController(updateGroupService);
exports.deleteGroupController = new controllers_1.DeleteGroupController(deleteGroupService);
exports.addUserAtGroupController = new controllers_1.AddUserAtGroupController(addUserAtGroupService);
exports.deleteUserAtGroupController = new controllers_1.DeleteUserAtGroupController(deleteUserAtGroupService);
exports.getUsersAtGroupController = new controllers_1.GetUsersAtGroupController(getUsersAtGroupService);
exports.addUserAtGroupByTokenController = new controllers_1.AddUserByTokenController(addUserByTokenService);
